server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5434/inventory
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.flashsale.inventory.events"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus