spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: auth
    password: auth
  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

security:
  jwt:
    issuer: flashsale-auth
    secret: "4adc46d0108bffc85f56acf526af842017b3ad6996476b28643ea3ae7c0c5210"
    accessTokenTtlMinutes: 60