server:
  port: 8085

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus