server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: orders
    password: orders
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.flashsale.order.events"
        spring.json.use.type.headers: false
    producer:
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    version: OPENAPI_3_0
  swagger-ui:
    enabled: ${API_DOCS_ENABLED:true}
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    persist-authorization: false
