server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://localhost:8086
              predicates:
                - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus