server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://localhost:8086
              predicates:
                - Path=/auth/**
            - id: catalog
              uri: http://localhost:8085
              predicates:
                - Path=/products/**
            - id: cart
              uri: http://localhost:8084
              predicates:
                - Path=/cart/**
            - id: orders
              uri: http://localhost:8081
              predicates:
                - Path=/orders/**
            - id: inventory
              uri: http://localhost:8081
              predicates:
                - Path=/inventory/**
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                exposedHeaders:
                  - "*"
                allowCredentials: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus